# Based on https://kodimensional.dev/github-actions

name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

env:
  cabalConfig: --enable-tests --enable-benchmarks --enable-deterministic --write-ghc-environment-files=always

jobs:
  cabal:
    name: ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: [latest]
        ghc: ['8.10']
      fail-fast: false

    steps:
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/checkout@v2

    - name: Repository update
      run: |
        cabal v2-update

    # NOTE: Freeze is for the caching
    - name: Configuration freeze
      run: |
        cabal v2-freeze $cabalConfig

    - uses: actions/cache@v1
      name: Cache cabal-store
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze')
          }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Install system dependencies
      run: sudo apt-get install libsodium-dev

    - name: Build dependencies
      run: |
        cabal build all --only-dependencies $cabalConfig

    - name: Build
      run: |
        cabal build all $cabalConfig

    - name: Test
      run: |
        cabal test all $cabalConfig

  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v13
    - uses: actions/checkout@v2
    - run: nix-build
